[package]
name = "atlas-rt-godot"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
godot = "0.5.5"
atlas-rt = { path = ".." }
glam = "0.30"

[lib]
crate-type = ["cdylib", "rlib"]

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
exit = "deny"
as_conversions = "deny"
too_many_arguments = "allow"
