[package]
name = "atlas-rt"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-taskgraph = { git = "https://github.com/vulkano-rs/vulkano" }
winit = "0.30"
dot_vox = "*"
glam = { version = "*", features = ["bytemuck"] }
anyhow = "1.0.104"
rayon = "1.12"
rustc-hash = "2"

[lints]
workspace = true
