#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_vulkanhooks = env_modules.Clone()

env_vulkanhooks.add_source_files(env.modules_sources, "*.cpp")
